# Objetivo do modulo:
# Reunir funcoes compartilhadas para padronizacao, validacao e orquestracao da camada silver.
# Processo:
# 1. Importar e re-exportar funcoes de dates, country_reference, framework,
#    methodology_reference, missing, normalize, numbers, quality_checks,
#    status_reference e text.
# 2. Servir como ponto unico de import para todos os builders silver.
# 3. Cada certificadora importa apenas deste modulo, sem referenciar submodulos diretamente.

from .dates import format_date_iso, format_datetime_iso, parse_date, parse_date_to_iso, parse_datetime, parse_datetime_to_iso
from .country_reference import (
    build_country_sync_parser,
    collect_default_country_rows,
    run_country_sync,
    sync_country_reference_projects,
    sync_country_reference_rows,
)
from .framework import (
    CandidateSource,
    FieldSpec,
    build_dataset_parser,
    extract_project_geometry,
    geometry_candidate,
    build_mapping_parser,
    build_mapping_markdown,
    build_mapping_rows,
    calculate_sample_size,
    derive_bronze_file_path,
    evaluate_candidate,
    first_non_empty,
    get_path,
    load_json,
    load_standard_acronym,
    parse_guide_fields,
    path_candidate,
    resolve_detail_files,
    run_dataset,
    run_mapping,
    select_sample_files,
    transform_project,
    transformed_candidate,
    validate_date,
    write_json,
)
from .missing import empty_to_none, is_missing, normalize_missing

from .methodology_reference import (
    build_methodology_sync_parser,
    collect_default_methodology_rows,
    normalize_project_methodology,
    run_methodology_sync,
    sync_methodology_reference_projects,
    sync_methodology_reference_rows,
)
from .normalize import ensure_list, normalize_record, normalize_record_value, scalar_or_list, unique_non_empty
from .numbers import parse_coordinate, parse_count, parse_decimal_measure, parse_integer, parse_number
from .quality_checks import collect_quality_issues, validate_date_fields, validate_numeric_fields, validate_required_fields
from .status_reference import (
    build_status_sync_parser,
    collect_default_status_rows,
    load_standard_sigla,
    run_status_sync,
    sync_status_reference_projects,
    sync_status_reference_rows,
)
from .text import collapse_whitespace, normalize_multiline_text, normalize_text, strip_text

__all__ = [
    "CandidateSource",
    "FieldSpec",
    "build_dataset_parser",
    "build_country_sync_parser",
    "extract_project_geometry",
    "geometry_candidate",
    "build_mapping_markdown",
    "build_mapping_parser",
    "build_mapping_rows",
    "calculate_sample_size",
    "collapse_whitespace",
    "collect_quality_issues",
    "collect_default_country_rows",
    "collect_default_methodology_rows",
    "derive_bronze_file_path",
    "empty_to_none",
    "ensure_list",
    "evaluate_candidate",
    "first_non_empty",
    "format_date_iso",
    "format_datetime_iso",
    "get_path",
    "is_missing",
    "load_json",
    "load_standard_acronym",
    "normalize_missing",
    "normalize_multiline_text",
    "normalize_record",
    "normalize_record_value",
    "normalize_text",
    "normalize_project_methodology",
    "parse_date",
    "parse_date_to_iso",
    "parse_datetime",
    "parse_datetime_to_iso",
    "parse_coordinate",
    "parse_count",
    "parse_decimal_measure",
    "parse_guide_fields",
    "parse_integer",
    "parse_number",
    "path_candidate",
    "resolve_detail_files",
    "run_dataset",
    "run_country_sync",
    "run_methodology_sync",
    "run_mapping",
    "run_status_sync",
    "scalar_or_list",
    "select_sample_files",
    "strip_text",
    "sync_status_reference_projects",
    "sync_status_reference_rows",
    "sync_country_reference_projects",
    "sync_methodology_reference_projects",
    "sync_country_reference_rows",
    "sync_methodology_reference_rows",
    "transform_project",
    "transformed_candidate",
    "unique_non_empty",
    "validate_date",
    "validate_date_fields",
    "validate_numeric_fields",
    "validate_required_fields",
    "write_json",
    "build_methodology_sync_parser",
    "build_status_sync_parser",
    "collect_default_status_rows",
    "load_standard_sigla",
]
